export const FOLDER_IMAGES = process.env.NEXT_PUBLIC_FOLDER_IMAGES;
export const FOLDER_PROCESSING = process.env.NEXT_PUBLIC_FOLDER_PROCESSING;
export const FOLDER_RESTORED = process.env.NEXT_PUBLIC_FOLDER_RESTORED;
export const BUCKET_IMAGE_URL = process.env.NEXT_PUBLIC_SUPABASE_APP_BUCKET_IMAGE_URL;

