export const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL
export const STORAGE_URL = process.env.NEXT_PUBLIC_SUPABASE_STORAGE_URL;
export const SUPABASE_BUCKET = process.env.NEXT_PUBLIC_SUPABASE_STORAGE_BUCKET;
export const FOLDER_PROCESSING = process.env.NEXT_PUBLIC_FOLDER_PROCESSING
export const FOLDER_RESTORED = process.env.NEXT_PUBLIC_FOLDER_RESTORED;

